### ISSUE TITLE
 git:// dependency and bower cannot find module

### ISSUE THREAD

**Issue by metasoarous** [pol-is/polisClientParticipation#33]
The following is from @urakagi (pol-is/polisServer#32):

I'm building `polisClientParticipant` on my new server, and when I `./deployPreprod` I get this error:

```
/home/romulus/polisClientParticipation/js/templates/settingsEnterprise.handlebars
module.js:442
    throw err;
    ^

Error: Cannot find module '/home/romulus/polisClientParticipation/bower_components/backbone/backbone'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.resolve (internal/module.js:27:19)
    at /home/romulus/polisClientParticipation/node_modules/browserify-shim/index.js:91:34
    at Array.forEach (native)
    at shim (/home/romulus/polisClientParticipation/node_modules/browserify-shim/index.js:86:6)
    at Transform.transform [as _transform] (/home/romulus/polisClientParticipation/node_modules/gulp-browserify/index.js:84:17)
```

The path seems weird since it repeats "backbone". Is this correct?

Also, there's some `git://github.io...` URLs in each `package.json` and `bower.json`, and my server's network does not allow `git://` protocol. Can we just use `https://` rather than `git://`? Does it have any advantage?

Thanks.

**Comment by metasoarous** [comment]
Thanks for posting @urakagi.

A few questions:

* Did you go through the setup instructions in the README (`npm install && bower install`) ? Any errors there?
* What do you see in `bower_components` & `bower_components/backbone` if anything?
* Were you able to get the deploy script to work prior to the recent updates you pulled?
* What do you get from `bower -v`?

I don't see a problem with the `backbone/backbone` module path; In my `bower_components/backbone/` directory, there is a `backbone.js` file, so this should be what is getting loaded up. Bower is basically a fossil, and we plan to get off (see pol-is/polisClientParticipation#34). But for the moment, I do have it working on `1.8.4`, which I got installing using `apt-get` on Ubuntu.

The main advantage of the `git` protocol is that if you need to make edits and push back up, it's a bit easier with the git protocol (authorize through ssh keys instead of GH username password). I don't know if there are any other issues with switching to https aside from this, but you're welcome to try it out and report back here.

**Comment by urakagi** [comment]
Hi @metasoarous,

1. Yes, all `git://` URL can't pass network and error with timeout, both for `package.json` and `bower.json`. I fixed them to `https://` and continued to next steps. For backbone, I changed to `https://github.com/mbjorkegren/backbone/tree/polis`.
2. I see a single file named 'index'.
3. It was on another machine with a free network, so I'm not sure.
4. I see `1.8.4`.

I didn't know `package.json` can be used to push back edits. I always use regular git :open_mouth:

**Comment by urakagi** [comment]
Also, I see this when `bower install`:

```
Unable to find a suitable version for backbone, please choose one by typing one of the numbers below:
    1) backbone#* and is required by dashboard-require
    2) backbone#1.0.0 which resolved to 1.0.0 and is required by thorax#2.0.3

Prefix the choice with ! to persist it to bower.json

? Answer
```

But both 1 and 2 only downloads an `index`. I think there's a problem with the replaced https url:
```
"backbone": "https://github.com/mbjorkegren/backbone",
"handlebones": "https://github.com/mbjorkegren/handlebones",
```

Also, the tailing `#polis` and `#master` in original URL will cause `bower install` error as it can't use `#` in URL.

**Comment by metasoarous** [comment]
I'm looking at Bower in greater detail, and it looks like for `https` dependencies are treated as single file resources, not as github repositories. So I don't think there's any way for you to get around using the `git` protocol here.

https://bower.io/

However, this really shouldn't be a problem for you not that I think about it more carefully. You don't need to run the deploy scripts from the server; The whole point of the deploy script is that it builds the JS source into a single asset/file, and pushes that up to either S3 or a static file server, depending on the settings in your `polis.config.js`. So you can really just run that build and push process from your dev computer and forget about the server.

> I didn't know package.json can be used to push back edits. I always use regular git :open_mouth:

I don't mean that I use `package.json` to push edits back up. I mean that when npm clones down a project, if it does so from a `git` url vs a `https` url, when you cd into that download directory and try running git commands, your `origin` remote is going to be set to the `git` url, and therefore you won't need to enter credentials every time you push.

**Comment by urakagi** [comment]
Okay so the two git dependencies have nothing to do with building?
Can you give me a hint that what should I extract from `gulpfile.js`? I don't know this build system, and it looks like compiling and uploading is not separated very well.

**Comment by colinmegill** [comment]
This is correct. That file encompasses both building and uploading and
should be modularized.

**Comment by urakagi** [comment]
I tried to let `gulp` only run `preprodConfig` and `dist` only, but the same error appears. It seems like `backbone` is needed for building.

**Comment by metasoarous** [comment]
@urakagi You should be able to manually download the backbone source code and place in the listed directory, if you really must run the build process from your server. But again, I'd encourage you to try from your dev machine, since there's really no reason to run this process from the server.

Let me know if I'm missing something here.

**Comment by urakagi** [comment]
Okay I'll go to build files on another dev machine.

**Comment by metasoarous** [comment]
Didn't think to ask before: Are you working directly logged into the server? I assumed you were logging in via SSH or something via a dev laptop or something, because that's what I usually do, but I shouldn't assume things.

**Comment by urakagi** [comment]
I'm logging into the server via SSH. But well, my desktop is Windows and I'm a quite loyal Windows user. Thus when I need a dev machine for polis, I log into another remote Linux machine via SSH. If I need IDE, I write codes on Windows, use git to push onto the dev machine, then build and run there.

**Comment by urakagi** [comment]
My office computer is Windows 7 :/

**Comment by patcon** [comment]
This seems to work:

```diff
diff --git a/client-participation/bower.json b/client-participation/bower.json
index 7028dc27..68f51db9 100644
--- a/client-participation/bower.json
+++ b/client-participation/bower.json
@@ -2,14 +2,14 @@
   "name": "dashboard-require",
   "version": "0.0.0",
   "dependencies": {
-    "backbone": "git://github.com/mbjorkegren/backbone#polis",
+    "backbone": "https://github.com/mbjorkegren/backbone.git#polis",
     "underscore": "~1.5.2",
     "thorax": "~2.0",
     "bootstrap": "~3.1.1",
     "d3": "~3.5.17",
     "font-awesome": "~4.1.0",
     "d3-tip": "<=0.6.4",
-    "handlebones": "git://github.com/mbjorkegren/handlebones#master",
+    "handlebones": "https://github.com/mbjorkegren/handlebones.git#master",
     "bootstrap-sass-official": "~3.2.0",
     "markdown": "~0.5.0",
     "deepcopy": "~0.4.0"
```

Could we make that change and close this out?
